name: CoolCratesPro
description: Simple crate plugin (Remastered)
author: David202020 & StrikeDevelopment
website: https://minehub.de
main: CoolCratesPro\Loader
load: POSTWORLD
version: "2.0"
api: [1.12.0, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
